#!/usr/bin/env python3
"""Smarthost Phase 1 environment and unit renderer (stdlib only).

Commands:
    env-example   regenerate infra/.env.example from docs/contracts/environment.md
    init-env      create infra/.env (gitignored) from the template with random
                  development secrets; never overwrites an existing file
    render        validate infra/.env against the contract, write one env file per
                  consumer (contract "Consumers" column - least privilege) and render
                  infra/podman/*.in (the persistent pod script) and infra/systemd/*.in
                  into infra/.generated/

Templates may reference only contract variables as ${VAR}, plus @REPO@ (the
repository path) and @GENERATED@ (infra/.generated). Anything else is an error,
so no undocumented variable can reach a service. In shell templates (*.sh.in)
every substituted value is shell-quoted, and the rendered script is executable.
"""
from __future__ import annotations

import base64
import os
import re
import secrets
import shlex
import stat
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "docs/contracts/environment.md"
EXAMPLE = ROOT / "infra/.env.example"
DOTENV = ROOT / "infra/.env"
GENERATED = ROOT / "infra/.generated"
TEMPLATE_DIRS = {"podman": ROOT / "infra/podman", "systemd": ROOT / "infra/systemd"}

ROW = re.compile(r"^\| `([A-Z][A-Z0-9_]*)` \| ([^|]+)\| (\*\*yes\*\*|no) \| ([^|]+)\| ([^|]*)\|", re.M)


def contract() -> list[dict]:
    text = CONTRACT.read_text(encoding="utf-8")
    rows = []
    for block in re.split(r"\n## ", text)[1:]:
        title = block.splitlines()[0].strip()
        for name, consumers, secret, phase, example in ROW.findall(block):
            rows.append({
                "section": title, "name": name, "secret": secret == "**yes**",
                "consumers": [c.strip() for c in consumers.split(",")],
                "phase": phase.strip(), "example": "" if secret == "**yes**" else example.strip().strip("`"),
            })
    return rows


def env_example() -> None:
    out = [
        "# Smarthost environment template — SAFE TO COMMIT, CONTAINS NO SECRETS.",
        "#",
        "# Contract: docs/contracts/environment.md (normative; consumers, phases, meanings).",
        "# Generated by: python3 infra/lib/smarthost_render.py env-example",
        "# For development run `infra/bin/smarthostctl init-env`, which copies this file to",
        "# infra/.env (gitignored) and fills the empty secrets with random development values.",
        "# Empty APP_RETENTION_* values mean 'no automatic deletion' until the",
        "# operator's compliance specification sets the production policy.",
        "# Each container receives only the variables listed as its consumers (rendered",
        "# per service into infra/.generated/env/ by `smarthostctl render`).",
        "",
    ]
    section = None
    for row in contract():
        if row["section"] != section:
            section = row["section"]
            out += ["# " + "-" * 70, f"# {section}", "# " + "-" * 70]
        tail = " | SECRET — leave empty here" if row["secret"] else ""
        out.append(f"# consumers: {', '.join(row['consumers'])} | phase {row['phase']}{tail}")
        out.append(f"{row['name']}={row['example']}")
    out.append("")
    EXAMPLE.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {EXAMPLE.relative_to(ROOT)}")


def parse_dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = re.match(r"^([A-Z][A-Z0-9_]*)=(.*)$", line)
        if not m:
            sys.exit(f"{path}:{lineno}: not KEY=value")
        values[m.group(1)] = m.group(2)
    return values


def dev_secret(name: str) -> str:
    if name == "APP_ENCRYPTION_KEYS":
        return "dev1:" + base64.b64encode(secrets.token_bytes(32)).decode()
    if name == "MAILER_DSN":
        return ""  # Smarthost's own notifications are not used in Phase 1
    return secrets.token_urlsafe(24)


def init_env() -> None:
    if DOTENV.exists():
        print(f"{DOTENV.relative_to(ROOT)} already exists; not overwriting")
        return
    lines = []
    for line in EXAMPLE.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^([A-Z][A-Z0-9_]*)=$", line)
        secret_names = {r["name"] for r in contract() if r["secret"]}
        if m and m.group(1) in secret_names:
            line = f"{m.group(1)}={dev_secret(m.group(1))}"
        lines.append(line)
    header = ["# DEVELOPMENT ONLY — generated by `smarthostctl init-env`. Never commit this file.", ""]
    DOTENV.write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    DOTENV.chmod(stat.S_IRUSR | stat.S_IWUSR)
    print(f"created {DOTENV.relative_to(ROOT)} with random development secrets (mode 0600)")


def render() -> None:
    rows = contract()
    names = {r["name"] for r in rows}
    if not DOTENV.exists():
        sys.exit("infra/.env missing: run `smarthostctl init-env` first")
    values = parse_dotenv(DOTENV)
    unknown = sorted(set(values) - names)
    missing = sorted(names - set(values))
    if unknown or missing:
        sys.exit(f"infra/.env does not match the contract: unknown={unknown} missing={missing}")
    if values["SMARTHOST_ENV"] == "production" and values["SMARTHOST_ALLOW_UNVERIFIED_SENDING_DOMAINS"] == "true":
        sys.exit("SMARTHOST_ALLOW_UNVERIFIED_SENDING_DOMAINS=true is forbidden in production")

    env_dir = GENERATED / "env"
    env_dir.mkdir(parents=True, exist_ok=True)
    os.chmod(GENERATED, 0o700)
    consumers = sorted({c for r in rows for c in r["consumers"]})
    for consumer in consumers:
        body = [f"# Generated for consumer '{consumer}' from infra/.env. Do not edit."]
        body += [f"{r['name']}={values[r['name']]}" for r in rows if consumer in r["consumers"]]
        target = env_dir / f"{consumer}.env"
        target.write_text("\n".join(body) + "\n", encoding="utf-8")
        target.chmod(stat.S_IRUSR | stat.S_IWUSR)

    placeholder = re.compile(r"\$\{([A-Za-z0-9_]+)\}")
    for kind, src_dir in TEMPLATE_DIRS.items():
        out_dir = GENERATED / kind
        out_dir.mkdir(parents=True, exist_ok=True)
        for old in out_dir.iterdir():
            old.unlink()
        for template in sorted(src_dir.glob("*.in")):
            text = template.read_text(encoding="utf-8")
            bad = sorted({m for m in placeholder.findall(text) if m not in names})
            if bad:
                sys.exit(f"{template.relative_to(ROOT)} references non-contract variables {bad}")
            shell = template.name.endswith(".sh.in")
            quote = shlex.quote if shell else (lambda v: v)
            text = placeholder.sub(lambda m: quote(values[m.group(1)]), text)
            text = text.replace("@REPO@", quote(str(ROOT))).replace("@GENERATED@", quote(str(GENERATED)))
            target = out_dir / template.name[:-3]
            target.write_text(text, encoding="utf-8")
            if shell:
                target.chmod(stat.S_IRWXU)
    print(f"rendered {len(consumers)} env files and units into {GENERATED.relative_to(ROOT)}/")


if __name__ == "__main__":
    commands = {"env-example": env_example, "init-env": init_env, "render": render}
    if len(sys.argv) != 2 or sys.argv[1] not in commands:
        sys.exit(f"usage: {sys.argv[0]} {{{'|'.join(commands)}}}")
    commands[sys.argv[1]]()
