<?php

declare(strict_types=1);

namespace App\Tests\Schema;

use App\Tests\Support\Catalog;
use App\Tests\Support\Db;
use PHPUnit\Framework\TestCase;

/**
 * Completion criterion 2: the database built by the Doctrine migrations (run by
 * the harness on an empty PostgreSQL 16 database) is structurally identical to
 * docs/schema/reference-schema.sql (loaded verbatim into <db>_reference).
 */
final class ReferenceSchemaEquivalenceTest extends TestCase
{
    public function testMigratedSchemaEqualsTheReferenceSchema(): void
    {
        $reference = Catalog::describe(Db::owner(Db::databaseName().'_reference'));
        $migrated = Catalog::describe(Db::owner());

        self::assertCount(48, $reference['tables']);
        self::assertSame([], Catalog::diff($reference, $migrated));
        // Sanity: the comparison really covers the objects.
        self::assertGreaterThan(250, \count($migrated['columns']));
        self::assertGreaterThan(100, \count($migrated['constraints']));
        self::assertGreaterThan(60, \count($migrated['indexes']));
    }

    public function testServerIsPostgres16(): void
    {
        self::assertStringStartsWith('16.', (string) Db::owner()->fetchOne('SHOW server_version'));
    }

    public function testNoEnumTypesNoCascadesNoIdDefaults(): void
    {
        $c = Db::owner();
        self::assertSame(0, (int) $c->fetchOne("SELECT count(*) FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typtype = 'e'"));
        self::assertSame(0, (int) $c->fetchOne("SELECT count(*) FROM pg_constraint WHERE contype = 'f' AND (confdeltype <> 'a' OR confupdtype <> 'a')"),
            'Foreign keys must be NO ACTION (history is never cascaded away).');
        self::assertSame(0, (int) $c->fetchOne("SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND column_name = 'id' AND column_default IS NOT NULL"),
            'UUIDv7 ids are generated by the writer, never by a database default.');
        self::assertSame(0, (int) $c->fetchOne("SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name <> 'doctrine_migration_versions' AND data_type = 'timestamp without time zone'"));
    }

    public function testMigrationsAreRecordedAndOwnedByTheSchemaOwner(): void
    {
        $c = Db::owner();
        self::assertSame(15, (int) $c->fetchOne('SELECT count(*) FROM doctrine_migration_versions'));
        $owners = $c->fetchFirstColumn("SELECT DISTINCT tableowner FROM pg_tables WHERE schemaname = 'public'");
        self::assertSame([Db::env('SMARTHOST_DB_OWNER_USER')], $owners);
    }
}
