// Package ids allocates the identifiers of a message (spec
// sending.per_recipient, schema identifier_strategy):
//
//   - message ids are UUIDv7 (time-ordered, RFC 9562), like every other id;
//   - VERP tokens are 128-bit CSPRNG values in lower-case base32 (26 chars of
//     [a-z2-7]). They are opaque, carry no personal data, and survive receivers
//     that lower-case the local part of a return path;
//   - tracking tokens are 192-bit CSPRNG values in base64url (32 chars), never
//     signed (spec message_tracking.engagement_tracking.tokens);
//   - the Message-ID header is <message_id@SMARTHOST_BOUNCE_DOMAIN>.
package ids

import (
	"crypto/rand"
	"encoding/base32"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"strings"
	"sync"
	"time"
)

var lowerB32 = base32.NewEncoding("abcdefghijklmnopqrstuvwxyz234567").WithPadding(base32.NoPadding)

func random(n int) []byte {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(fmt.Sprintf("crypto/rand: %v", err)) // never happens on Linux; never fall back to a weak source
	}
	return b
}

// VERPToken returns a new 128-bit lower-case base32 token.
func VERPToken() string { return lowerB32.EncodeToString(random(16)) }

// TrackingToken returns a new 192-bit base64url token (32 characters).
func TrackingToken() string { return base64.RawURLEncoding.EncodeToString(random(24)) }

var (
	v7mu   sync.Mutex
	v7last int64
	v7seq  uint16
)

// UUIDv7 returns a new RFC 9562 version-7 UUID string. Within one millisecond
// the 12-bit rand_a field is a counter seeded randomly, so ids generated by one
// process are strictly increasing.
func UUIDv7() string {
	var u [16]byte
	copy(u[:], random(16))
	ms := time.Now().UnixMilli()
	v7mu.Lock()
	if ms <= v7last {
		ms = v7last
		v7seq++
		if v7seq > 0x0fff { // counter exhausted: borrow the next millisecond
			ms++
			v7seq = uint16(binary.BigEndian.Uint16(u[6:8])) & 0x07ff
		}
	} else {
		v7seq = uint16(binary.BigEndian.Uint16(u[6:8])) & 0x07ff
	}
	v7last = ms
	seq := v7seq
	v7mu.Unlock()
	u[0], u[1], u[2], u[3], u[4], u[5] = byte(ms>>40), byte(ms>>32), byte(ms>>24), byte(ms>>16), byte(ms>>8), byte(ms)
	u[6] = 0x70 | byte(seq>>8&0x0f)
	u[7] = byte(seq)
	u[8] = u[8]&0x3f | 0x80 // RFC 9562 variant
	h := fmt.Sprintf("%x", u)
	return h[0:8] + "-" + h[8:12] + "-" + h[12:16] + "-" + h[16:20] + "-" + h[20:32]
}

// MessageIDHeader is the RFC 5322 Message-ID of a message.
func MessageIDHeader(messageID, bounceDomain string) string {
	return "<" + messageID + "@" + bounceDomain + ">"
}

// ParseMessageIDHeader returns the Smarthost message id inside a Message-ID
// value ("<uuid@bounce-domain>") when it carries one for bounceDomain.
func ParseMessageIDHeader(v, bounceDomain string) (string, bool) {
	v = strings.TrimSpace(v)
	if !strings.HasPrefix(v, "<") || !strings.HasSuffix(v, ">") {
		return "", false
	}
	v = v[1 : len(v)-1]
	at := strings.LastIndexByte(v, '@')
	if at < 0 || !strings.EqualFold(v[at+1:], bounceDomain) || !IsUUID(v[:at]) {
		return "", false
	}
	return strings.ToLower(v[:at]), true
}

// IsUUID reports whether s is a canonical (8-4-4-4-12 hex) UUID.
func IsUUID(s string) bool {
	if len(s) != 36 {
		return false
	}
	for i, c := range s {
		switch i {
		case 8, 13, 18, 23:
			if c != '-' {
				return false
			}
		default:
			if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f' || c >= 'A' && c <= 'F') {
				return false
			}
		}
	}
	return true
}

// VERP builds and parses envelope return paths
// (<local-part><delimiter><token>@<bounce domain>).
type VERP struct{ LocalPart, Delimiter, Domain string }

// ReturnPath is the envelope MAIL FROM of a message.
func (v VERP) ReturnPath(token string) string {
	return v.LocalPart + v.Delimiter + token + "@" + v.Domain
}

// Token extracts the VERP token from a bounce-domain recipient address
// (case-insensitively, as receivers may change case). It is the correlation
// prerequisite for inbound DSNs (Phase 5).
func (v VERP) Token(address string) (string, bool) {
	at := strings.LastIndexByte(address, '@')
	if at < 0 || !strings.EqualFold(address[at+1:], v.Domain) {
		return "", false
	}
	local := strings.ToLower(address[:at])
	prefix := strings.ToLower(v.LocalPart + v.Delimiter)
	if !strings.HasPrefix(local, prefix) {
		return "", false
	}
	tok := local[len(prefix):]
	if len(tok) != 26 {
		return "", false
	}
	for _, c := range tok {
		if !(c >= 'a' && c <= 'z' || c >= '2' && c <= '7') {
			return "", false
		}
	}
	return tok, true
}
