<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Send jobs, staged recipient batches, messages, events, unmatched DSNs, ingest cursors (D-01, D-05, D-06, D-16, D-24).
 *
 * Reproduces the "Sending" section of docs/schema/reference-schema.sql
 * (specification 2.1); tests/Schema/ReferenceSchemaEquivalenceTest.php proves the
 * resulting catalog is structurally identical. Conventions: UUIDv7 ids generated by
 * the writer (no DB default), timestamptz, text + CHECK enums, NO ACTION foreign
 * keys. Roles and grants are infrastructure (infra/postgres/grants.sql).
 */
final class Version20261003000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Send jobs, staged recipient batches, messages, events, unmatched DSNs, ingest cursors (D-01, D-05, D-06, D-16, D-24)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE send_jobs (
    id                     uuid        PRIMARY KEY,
    client_id              uuid        NOT NULL REFERENCES clients (id),
    external_reference     text        NOT NULL,
    idempotency_key        text        NOT NULL,
    request_hash           text        NOT NULL,
    message_class          text        NOT NULL CHECK (message_class IN ('transactional', 'subscription')),
    list_id                text        NULL,
    sending_domain_id      uuid        NOT NULL REFERENCES sending_domains (id),
    sender_email           text        NOT NULL,
    sender_name            text        NULL,
    reply_to_email         text        NULL,
    reply_to_name          text        NULL,
    track_opens            boolean     NOT NULL DEFAULT false,
    track_clicks           boolean     NOT NULL DEFAULT false,
    status                 text        NOT NULL DEFAULT 'collecting'
        CHECK (status IN ('collecting', 'queued', 'processing', 'dispatched', 'completed', 'failed', 'cancelled')),
    created_at             timestamptz NOT NULL DEFAULT now(),
    queued_at              timestamptz NULL,
    started_at             timestamptz NULL,
    dispatch_completed_at  timestamptz NULL,
    completed_at           timestamptz NULL,
    total_recipients       integer     NOT NULL DEFAULT 0 CHECK (total_recipients BETWEEN 0 AND 10000),
    summary_counts_json    jsonb       NOT NULL DEFAULT '{}'::jsonb,
    claimed_by             text        NULL,
    lease_expires_at       timestamptz NULL,
    attempt_count          integer     NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_error             text        NULL,
    CONSTRAINT send_jobs_list_id_by_class CHECK ((message_class = 'subscription') = (list_id IS NOT NULL)),
    CONSTRAINT send_jobs_reply_to_complete CHECK (reply_to_name IS NULL OR reply_to_email IS NOT NULL),
    CONSTRAINT send_jobs_sealed CHECK (
        status IN ('collecting', 'cancelled') OR (queued_at IS NOT NULL AND total_recipients >= 1)),
    CONSTRAINT send_jobs_dispatched_has_time CHECK (
        status NOT IN ('dispatched', 'completed') OR dispatch_completed_at IS NOT NULL),
    CONSTRAINT send_jobs_completed_has_time CHECK (status <> 'completed' OR completed_at IS NOT NULL)
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX send_jobs_client_idempotency_uq ON send_jobs (client_id, idempotency_key)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX send_jobs_client_status_idx ON send_jobs (client_id, status)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX send_jobs_client_external_ref_idx ON send_jobs (client_id, external_reference)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX send_jobs_claimable_idx ON send_jobs (queued_at, lease_expires_at) WHERE status IN ('queued', 'processing')
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX send_jobs_awaiting_completion_idx ON send_jobs (dispatch_completed_at) WHERE status = 'dispatched'
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX send_jobs_collecting_idx ON send_jobs (created_at) WHERE status = 'collecting'
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE send_job_recipient_batches (
    id               uuid        PRIMARY KEY,
    send_job_id      uuid        NOT NULL REFERENCES send_jobs (id),
    idempotency_key  text        NOT NULL,
    request_hash     text        NOT NULL,
    recipient_count  integer     NOT NULL CHECK (recipient_count BETWEEN 1 AND 500),
    created_at       timestamptz NOT NULL DEFAULT now()
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX send_job_recipient_batches_job_key_uq ON send_job_recipient_batches (send_job_id, idempotency_key)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE send_job_recipients (
    id                            uuid        PRIMARY KEY,
    send_job_id                   uuid        NOT NULL REFERENCES send_jobs (id),
    batch_id                      uuid        NOT NULL REFERENCES send_job_recipient_batches (id),
    external_recipient_reference  text        NOT NULL,
    email_address                 text        NOT NULL,
    normalized_address            text        NOT NULL,
    subject                       text        NULL,
    html_body                     text        NULL,
    text_body                     text        NULL,
    unsubscribe_url               text        NULL CHECK (unsubscribe_url ~ '^https://'),
    content_bytes                 integer     NOT NULL CHECK (content_bytes >= 0),
    content_sha256                text        NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    content_purged_at             timestamptz NULL,
    created_at                    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT send_job_recipients_content_state CHECK (
        (content_purged_at IS NULL AND subject IS NOT NULL AND (html_body IS NOT NULL OR text_body IS NOT NULL))
     OR (content_purged_at IS NOT NULL AND subject IS NULL AND html_body IS NULL AND text_body IS NULL))
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX send_job_recipients_send_job_idx ON send_job_recipients (send_job_id, id)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX send_job_recipients_job_address_uq ON send_job_recipients (send_job_id, normalized_address)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX send_job_recipients_unpurged_idx ON send_job_recipients (created_at) WHERE content_purged_at IS NULL
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE messages (
    id                            uuid        PRIMARY KEY,
    send_job_id                   uuid        NOT NULL REFERENCES send_jobs (id),
    send_job_recipient_id         uuid        NOT NULL REFERENCES send_job_recipients (id),
    external_recipient_reference  text        NOT NULL,
    recipient_address             text        NOT NULL,
    verp_token                    text        NOT NULL,
    return_path                   text        NOT NULL,
    tracking_token                text        NULL CHECK (tracking_token ~ '^[A-Za-z0-9_-]{32,}$'),
    postfix_queue_id              text        NULL,
    current_status                text        NOT NULL DEFAULT 'created'
        CHECK (current_status IN ('created', 'queued', 'submitted', 'deferred', 'outcome_unknown',
                                  'remote_accepted', 'soft_bounced', 'hard_bounced', 'complained',
                                  'failed', 'suppressed')),
    created_at                    timestamptz NOT NULL DEFAULT now(),
    resolved_at                   timestamptz NULL
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX messages_send_job_id_idx ON messages (send_job_id, id)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX messages_send_job_status_idx ON messages (send_job_id, current_status)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX messages_send_job_recipient_uq ON messages (send_job_recipient_id)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX messages_verp_token_uq ON messages (verp_token)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX messages_tracking_token_uq ON messages (tracking_token) WHERE tracking_token IS NOT NULL
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX messages_postfix_queue_id_idx ON messages (postfix_queue_id) WHERE postfix_queue_id IS NOT NULL
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX messages_unresolved_idx ON messages (current_status, created_at)
    WHERE current_status IN ('queued', 'submitted', 'deferred')
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE message_links (
    id          uuid        PRIMARY KEY,
    message_id  uuid        NOT NULL REFERENCES messages (id),
    link_index  integer     NOT NULL CHECK (link_index >= 1),
    target_url  text        NOT NULL CHECK (target_url ~* '^https?://'),
    created_at  timestamptz NOT NULL DEFAULT now()
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX message_links_message_link_uq ON message_links (message_id, link_index)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE message_events (
    id                    uuid        PRIMARY KEY,
    message_id            uuid        NOT NULL REFERENCES messages (id),
    event_type            text        NOT NULL CHECK (event_type IN (
        'message_created', 'message_queued', 'message_suppressed', 'submission_failed',
        'submitted_to_postfix', 'postfix_queued', 'delivery_attempt', 'deferred',
        'connection_failure', 'remote_accepted', 'soft_bounce', 'hard_bounce',
        'complaint', 'transport_outcome_unknown', 'open_recorded', 'click_recorded',
        'dsn_unmatched')),
    event_source          text        NOT NULL CHECK (event_source IN (
        'delivery_daemon', 'postfix_submission', 'postfix_log', 'dsn_spool',
        'unmatched_dsn_resolution', 'queue_reconciliation', 'tracking_endpoint')),
    source_event_key      text        NULL,
    failure_scope         text        NULL CHECK (failure_scope IN (
        'recipient', 'domain', 'provider_policy', 'connection', 'dns', 'infrastructure', 'unknown')),
    smtp_code             smallint    NULL CHECK (smtp_code BETWEEN 200 AND 599),
    enhanced_status_code  text        NULL CHECK (enhanced_status_code ~ '^[245]\.[0-9]{1,3}\.[0-9]{1,3}$'),
    remote_host           text        NULL,
    diagnostic            text        NULL,
    metadata_json         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    occurred_at           timestamptz NOT NULL,
    recorded_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT message_events_tracking_unkeyed CHECK (event_source <> 'tracking_endpoint' OR source_event_key IS NULL),
    CONSTRAINT message_events_transport_keyed CHECK (event_source = 'tracking_endpoint' OR source_event_key IS NOT NULL),
    CONSTRAINT message_events_failure_scope_applicable CHECK (
        failure_scope IS NULL OR event_type IN ('deferred', 'connection_failure', 'soft_bounce', 'hard_bounce'))
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX message_events_message_occurred_idx ON message_events (message_id, occurred_at, id)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX message_events_source_key_uq ON message_events (event_source, source_event_key)
    WHERE source_event_key IS NOT NULL
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX message_events_soft_bounce_idx ON message_events (message_id, occurred_at)
    WHERE event_type IN ('soft_bounce', 'remote_accepted')
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE unmatched_dsns (
    id                       uuid        PRIMARY KEY,
    received_at              timestamptz NOT NULL,
    spool_ingest_key         text        NOT NULL,
    content_sha256           text        NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    classification           text        NOT NULL CHECK (classification IN (
        'hard_bounce', 'soft_bounce', 'deferred', 'connection_failure',
        'complaint', 'malformed_or_unmatched_dsn')),
    status                   text        NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'match_requested', 'matched', 'dismissed')),
    verp_token               text        NULL,
    original_recipient       text        NULL,
    final_recipient          text        NULL,
    postfix_queue_id         text        NULL,
    reporting_mta            text        NULL,
    enhanced_status_code     text        NULL,
    raw_message              text        NOT NULL,
    detail_json              jsonb       NOT NULL DEFAULT '{}'::jsonb,
    matched_message_id       uuid        NULL REFERENCES messages (id),
    resolution_requested_by  uuid        NULL REFERENCES users (id),
    resolution_requested_at  timestamptz NULL,
    resolution_event_id      uuid        NULL REFERENCES message_events (id),
    resolution_note          text        NULL,
    resolved_at              timestamptz NULL,
    CONSTRAINT unmatched_dsns_match_requested CHECK (
        status NOT IN ('match_requested', 'matched')
        OR (matched_message_id IS NOT NULL AND resolution_requested_by IS NOT NULL AND resolution_requested_at IS NOT NULL)),
    CONSTRAINT unmatched_dsns_matched_complete CHECK (
        status <> 'matched' OR (resolution_event_id IS NOT NULL AND resolved_at IS NOT NULL)),
    CONSTRAINT unmatched_dsns_dismissed_resolved CHECK (status <> 'dismissed' OR resolved_at IS NOT NULL)
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX unmatched_dsns_status_received_idx ON unmatched_dsns (status, received_at)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX unmatched_dsns_spool_key_uq ON unmatched_dsns (spool_ingest_key)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE delivery_ingest_cursors (
    source         text        PRIMARY KEY,
    generation_id  text        NOT NULL,
    position       bigint      NOT NULL CHECK (position >= 0),
    updated_at     timestamptz NOT NULL DEFAULT now()
)
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE delivery_ingest_cursors');
        $this->addSql('DROP TABLE unmatched_dsns');
        $this->addSql('DROP TABLE message_events');
        $this->addSql('DROP TABLE message_links');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE send_job_recipients');
        $this->addSql('DROP TABLE send_job_recipient_batches');
        $this->addSql('DROP TABLE send_jobs');
    }
}
