<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Validation jobs, addresses, evidence and the disposable-domain list.
 *
 * Reproduces the "Validation" section of docs/schema/reference-schema.sql
 * (specification 2.1); tests/Schema/ReferenceSchemaEquivalenceTest.php proves the
 * resulting catalog is structurally identical. Conventions: UUIDv7 ids generated by
 * the writer (no DB default), timestamptz, text + CHECK enums, NO ACTION foreign
 * keys. Roles and grants are infrastructure (infra/postgres/grants.sql).
 */
final class Version20261003000200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Validation jobs, addresses, evidence and the disposable-domain list';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE validation_jobs (
    id                          uuid        PRIMARY KEY,
    client_id                   uuid        NOT NULL REFERENCES clients (id),
    external_reference          text        NULL,
    idempotency_key             text        NOT NULL,
    request_hash                text        NOT NULL,
    status                      text        NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'processing', 'completed', 'failed', 'cancelled')),
    submitted_at                timestamptz NOT NULL DEFAULT now(),
    started_at                  timestamptz NULL,
    completed_at                timestamptz NULL,
    total_addresses             integer     NOT NULL CHECK (total_addresses BETWEEN 1 AND 10000),
    processed_count             integer     NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    classification_counts_json  jsonb       NOT NULL DEFAULT '{}'::jsonb
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX validation_jobs_client_idempotency_uq ON validation_jobs (client_id, idempotency_key)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX validation_jobs_client_status_idx ON validation_jobs (client_id, status)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX validation_jobs_client_external_ref_idx ON validation_jobs (client_id, external_reference)
    WHERE external_reference IS NOT NULL
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE validation_addresses (
    id                          uuid        PRIMARY KEY,
    job_id                      uuid        NOT NULL REFERENCES validation_jobs (id),
    external_address_reference  text        NULL,
    original_address            text        NOT NULL,
    normalized_address          text        NULL,
    syntax_status               text        NULL CHECK (syntax_status IN ('valid', 'invalid')),
    domain_status               text        NULL CHECK (domain_status IN (
        'mx', 'null_mx', 'address_fallback', 'no_mail_host', 'nxdomain',
        'temporary_failure', 'invalid_response', 'skipped')),
    smtp_status                 text        NULL CHECK (smtp_status IN (
        'accepted', 'rejected', 'temporary_failure', 'blocked', 'timeout',
        'connection_failed', 'inconclusive', 'skipped')),
    is_role                     boolean     NULL,
    is_disposable               boolean     NULL,
    is_catch_all_or_accept_all  boolean     NULL,
    is_domain_typo_suspected    boolean     NULL,
    suggested_address           text        NULL,
    suggestion_reason_code      text        NULL CHECK (suggestion_reason_code IN (
        'provider_domain_edit_distance', 'transposition', 'tld_typo',
        'legacy_domain_alias', 'other_domain_typo_rule')),
    suggestion_confidence       text        NULL CHECK (suggestion_confidence IN ('low', 'medium', 'high')),
    overall_classification      text        NULL CHECK (overall_classification IN (
        'deliverable', 'probably_deliverable', 'undeliverable',
        'temporarily_unverifiable', 'unknown', 'risky')),
    confidence                  text        NULL CHECK (confidence IN ('low', 'medium', 'high')),
    diagnostic_code             text        NULL,
    diagnostic_text             text        NULL,
    checked_at                  timestamptz NULL,
    processing_state            text        NOT NULL DEFAULT 'pending'
        CHECK (processing_state IN ('pending', 'claimed', 'retry_scheduled', 'done')),
    claimed_by                  text        NULL,
    lease_expires_at            timestamptz NULL,
    attempt_count               integer     NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at             timestamptz NULL,
    last_error                  text        NULL,
    CONSTRAINT validation_addresses_done_has_result CHECK (
        processing_state <> 'done' OR (overall_classification IS NOT NULL AND checked_at IS NOT NULL)),
    CONSTRAINT validation_addresses_claim_has_lease CHECK (
        processing_state <> 'claimed' OR (claimed_by IS NOT NULL AND lease_expires_at IS NOT NULL)),
    CONSTRAINT validation_addresses_suggestion_complete CHECK (
        (suggested_address IS NULL) = (suggestion_reason_code IS NULL)
        AND (suggested_address IS NULL) = (suggestion_confidence IS NULL))
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX validation_addresses_job_id_idx ON validation_addresses (job_id, id)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX validation_addresses_normalized_address_idx ON validation_addresses (normalized_address)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX validation_addresses_claimable_idx ON validation_addresses (processing_state, next_attempt_at, lease_expires_at)
    WHERE processing_state <> 'done'
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE validation_evidence (
    id                     uuid        PRIMARY KEY,
    validation_address_id  uuid        NOT NULL REFERENCES validation_addresses (id),
    evidence_type          text        NOT NULL CHECK (evidence_type IN (
        'dns_mx', 'dns_address', 'smtp_connect', 'smtp_ehlo', 'smtp_mail_from',
        'smtp_rcpt_to', 'smtp_accept_all_probe')),
    provider_host          text        NULL,
    response_code          smallint    NULL,
    enhanced_status_code   text        NULL,
    detail_json            jsonb       NOT NULL DEFAULT '{}'::jsonb,
    occurred_at            timestamptz NOT NULL
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX validation_evidence_address_occurred_idx ON validation_evidence (validation_address_id, occurred_at)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE disposable_domains (
    domain            text        PRIMARY KEY CHECK (domain = lower(domain)),
    source            text        NOT NULL,
    added_at          timestamptz NOT NULL DEFAULT now(),
    last_verified_at  timestamptz NULL
)
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE disposable_domains');
        $this->addSql('DROP TABLE validation_evidence');
        $this->addSql('DROP TABLE validation_addresses');
        $this->addSql('DROP TABLE validation_jobs');
    }
}
