<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Tenancy, people, sending domains and API keys (D-12, D-13, D-26).
 *
 * Reproduces the "Tenancy, people, domains and authentication" section of docs/schema/reference-schema.sql
 * (specification 2.1); tests/Schema/ReferenceSchemaEquivalenceTest.php proves the
 * resulting catalog is structurally identical. Conventions: UUIDv7 ids generated by
 * the writer (no DB default), timestamptz, text + CHECK enums, NO ACTION foreign
 * keys. Roles and grants are infrastructure (infra/postgres/grants.sql).
 */
final class Version20261003000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tenancy, people, sending domains and API keys (D-12, D-13, D-26)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE clients (
    id             uuid        PRIMARY KEY,
    company_name   text        NOT NULL,
    contact_email  text        NOT NULL,
    status         text        NOT NULL DEFAULT 'pending_approval'
        CHECK (status IN ('pending_approval', 'active', 'throttled', 'suspended', 'closed')),
    plan           text        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now()
)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE users (
    id             uuid        PRIMARY KEY,
    email          text        NOT NULL,
    password_hash  text        NULL,
    display_name   text        NULL,
    global_role    text        NULL CHECK (global_role IN ('operator')),
    status         text        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at     timestamptz NOT NULL DEFAULT now(),
    last_login_at  timestamptz NULL,
    disabled_at    timestamptz NULL
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX users_email_uq ON users (lower(email))
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE client_memberships (
    id          uuid        PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES users (id),
    client_id   uuid        NOT NULL REFERENCES clients (id),
    role        text        NOT NULL CHECK (role IN ('admin', 'member', 'viewer')),
    created_at  timestamptz NOT NULL DEFAULT now()
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX client_memberships_user_client_uq ON client_memberships (user_id, client_id)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX client_memberships_client_idx ON client_memberships (client_id)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE sending_domains (
    id                  uuid        PRIMARY KEY,
    client_id           uuid        NOT NULL REFERENCES clients (id),
    domain              text        NOT NULL CHECK (domain = lower(domain) AND position('@' IN domain) = 0),
    status              text        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'disabled')),
    verification_token  text        NOT NULL CHECK (verification_token ~ '^[A-Za-z0-9_-]{22,}$'),
    verified_at         timestamptz NULL,
    last_checked_at     timestamptz NULL,
    last_check_error    text        NULL,
    dkim_selector       text        NULL,
    dkim_status         text        NOT NULL DEFAULT 'not_configured'
        CHECK (dkim_status IN ('not_configured', 'pending_dns', 'active', 'disabled')),
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT sending_domains_verified_has_time CHECK (status <> 'verified' OR verified_at IS NOT NULL),
    CONSTRAINT sending_domains_dkim_has_selector CHECK (dkim_status = 'not_configured' OR dkim_selector IS NOT NULL)
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX sending_domains_client_domain_uq ON sending_domains (client_id, domain)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX sending_domains_domain_idx ON sending_domains (domain)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE api_keys (
    id            uuid        PRIMARY KEY,
    client_id     uuid        NOT NULL REFERENCES clients (id),
    key_hash      text        NOT NULL CHECK (key_hash ~ '^[0-9a-f]{64}$'),
    key_prefix    text        NOT NULL,
    name          text        NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_used_at  timestamptz NULL,
    revoked_at    timestamptz NULL
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX api_keys_key_hash_uq ON api_keys (key_hash)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX api_keys_client_id_idx ON api_keys (client_id)
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE api_keys');
        $this->addSql('DROP TABLE sending_domains');
        $this->addSql('DROP TABLE client_memberships');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE clients');
    }
}
