<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Usage metering, webhook endpoints/outbox/deliveries (D-10, D-22) and the audit log.
 *
 * Reproduces the "Metering, webhooks, audit" section of docs/schema/reference-schema.sql
 * (specification 2.1); tests/Schema/ReferenceSchemaEquivalenceTest.php proves the
 * resulting catalog is structurally identical. Conventions: UUIDv7 ids generated by
 * the writer (no DB default), timestamptz, text + CHECK enums, NO ACTION foreign
 * keys. Roles and grants are infrastructure (infra/postgres/grants.sql).
 */
final class Version20261003000500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Usage metering, webhook endpoints/outbox/deliveries (D-10, D-22) and the audit log';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE usage_records (
    id              uuid        PRIMARY KEY,
    client_id       uuid        NOT NULL REFERENCES clients (id),
    usage_type      text        NOT NULL CHECK (usage_type IN ('validation_address', 'message_submitted')),
    quantity        bigint      NOT NULL CHECK (quantity > 0),
    reference_type  text        NOT NULL CHECK (reference_type IN ('validation_job', 'send_job', 'message')),
    reference_id    uuid        NOT NULL,
    occurred_at     timestamptz NOT NULL
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX usage_records_client_occurred_idx ON usage_records (client_id, occurred_at)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX usage_records_reference_idx ON usage_records (reference_type, reference_id)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE webhook_endpoints (
    id                                  uuid        PRIMARY KEY,
    client_id                           uuid        NOT NULL REFERENCES clients (id),
    url                                 text        NOT NULL CHECK (url ~* '^https?://'),
    status                              text        NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
    subscribed_event_types              jsonb       NOT NULL CHECK (jsonb_typeof(subscribed_event_types) = 'array'),
    signing_secret_ciphertext           text        NOT NULL,
    signing_secret_key_id               text        NOT NULL,
    signing_secret_created_at           timestamptz NOT NULL DEFAULT now(),
    previous_signing_secret_ciphertext  text        NULL,
    previous_signing_secret_key_id      text        NULL,
    previous_signing_secret_expires_at  timestamptz NULL,
    created_at                          timestamptz NOT NULL DEFAULT now(),
    updated_at                          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT webhook_endpoints_previous_secret_complete CHECK (
        (previous_signing_secret_ciphertext IS NULL) = (previous_signing_secret_expires_at IS NULL)
        AND (previous_signing_secret_ciphertext IS NULL) = (previous_signing_secret_key_id IS NULL))
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX webhook_endpoints_client_idx ON webhook_endpoints (client_id)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE webhook_events (
    id             uuid        PRIMARY KEY,
    client_id      uuid        NOT NULL REFERENCES clients (id),
    event_type     text        NOT NULL CHECK (event_type IN (
        'validation.completed', 'validation.failed', 'send.completed', 'send.failed',
        'message.hard_bounced', 'message.complained', 'webhook.test')),
    subject_type   text        NOT NULL CHECK (subject_type IN ('validation_job', 'send_job', 'message', 'webhook_endpoint')),
    subject_id     uuid        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    fanned_out_at  timestamptz NULL
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX webhook_events_pending_fanout_idx ON webhook_events (created_at) WHERE fanned_out_at IS NULL
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX webhook_events_once_uq ON webhook_events (event_type, subject_id)
    WHERE event_type <> 'webhook.test'
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE webhook_deliveries (
    id                    uuid        PRIMARY KEY,
    client_id             uuid        NOT NULL REFERENCES clients (id),
    webhook_event_id      uuid        NOT NULL REFERENCES webhook_events (id),
    webhook_endpoint_id   uuid        NOT NULL REFERENCES webhook_endpoints (id),
    event_type            text        NOT NULL CHECK (event_type IN (
        'validation.completed', 'validation.failed', 'send.completed', 'send.failed',
        'message.hard_bounced', 'message.complained', 'webhook.test')),
    payload_json          jsonb       NOT NULL,
    payload_hash          text        NOT NULL,
    status                text        NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'delivered', 'failed')),
    attempt_count         integer     NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at       timestamptz NULL,
    claimed_by            text        NULL,
    lease_expires_at      timestamptz NULL,
    last_response_status  smallint    NULL,
    last_error            text        NULL,
    delivered_at          timestamptz NULL,
    created_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT webhook_deliveries_delivered_has_time CHECK (status <> 'delivered' OR delivered_at IS NOT NULL)
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX webhook_deliveries_due_idx ON webhook_deliveries (status, next_attempt_at) WHERE status = 'pending'
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX webhook_deliveries_client_created_idx ON webhook_deliveries (client_id, created_at)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX webhook_deliveries_event_endpoint_uq ON webhook_deliveries (webhook_event_id, webhook_endpoint_id)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE audit_log (
    id           uuid        PRIMARY KEY,
    actor_type   text        NOT NULL CHECK (actor_type IN ('user', 'api_key', 'system')),
    actor_id     text        NULL,
    action       text        NOT NULL,
    target_type  text        NOT NULL,
    target_id    text        NULL,
    detail_json  jsonb       NOT NULL DEFAULT '{}'::jsonb,
    occurred_at  timestamptz NOT NULL DEFAULT now()
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX audit_log_target_idx ON audit_log (target_type, target_id, occurred_at)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX audit_log_occurred_idx ON audit_log (occurred_at)
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE webhook_deliveries');
        $this->addSql('DROP TABLE webhook_events');
        $this->addSql('DROP TABLE webhook_endpoints');
        $this->addSql('DROP TABLE usage_records');
    }
}
