<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Suppressions and domain reputation.
 *
 * Reproduces the "Suppression and reputation" section of docs/schema/reference-schema.sql
 * (specification 2.1); tests/Schema/ReferenceSchemaEquivalenceTest.php proves the
 * resulting catalog is structurally identical. Conventions: UUIDv7 ids generated by
 * the writer (no DB default), timestamptz, text + CHECK enums, NO ACTION foreign
 * keys. Roles and grants are infrastructure (infra/postgres/grants.sql).
 */
final class Version20261003000400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Suppressions and domain reputation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE suppressions (
    id                 uuid        PRIMARY KEY,
    client_id          uuid        NULL REFERENCES clients (id),
    address_or_domain  text        NOT NULL,
    scope_type         text        NOT NULL CHECK (scope_type IN ('address', 'domain')),
    reason             text        NOT NULL CHECK (reason IN (
        'hard_bounce', 'complaint', 'repeated_soft_bounce', 'operator_block', 'client_abuse_block')),
    source_message_id  uuid        NULL REFERENCES messages (id),
    created_at         timestamptz NOT NULL DEFAULT now(),
    expires_at         timestamptz NULL,
    lifted_at          timestamptz NULL,
    CONSTRAINT suppressions_normalised CHECK (
        (scope_type = 'domain'  AND address_or_domain = lower(address_or_domain)
                                AND position('@' IN address_or_domain) = 0)
     OR (scope_type = 'address' AND address_or_domain ~ '@[^@]+$'
                                AND substring(address_or_domain FROM '@([^@]+)$')
                                    = lower(substring(address_or_domain FROM '@([^@]+)$'))))
)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX suppressions_address_or_domain_scope_idx ON suppressions (address_or_domain, scope_type)
SQL);
        $this->addSql(<<<'SQL'
CREATE INDEX suppressions_client_idx ON suppressions (client_id)
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE domain_reputation (
    id                  uuid        PRIMARY KEY,
    client_id           uuid        NULL REFERENCES clients (id),
    destination_domain  text        NOT NULL CHECK (destination_domain = lower(destination_domain)),
    metrics_json        jsonb       NOT NULL DEFAULT '{}'::jsonb,
    last_updated_at     timestamptz NOT NULL
)
SQL);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX domain_reputation_client_domain_uq
    ON domain_reputation (client_id, destination_domain) NULLS NOT DISTINCT
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE domain_reputation');
        $this->addSql('DROP TABLE suppressions');
    }
}
