-- =============================================================================
-- Smarthost reference schema — specification 2.7 (PostgreSQL 16; D-30 in 2.4, D-38 in 2.5, engagement index in 2.6, access control in 2.7)
-- =============================================================================
--
-- THIS IS NOT A MIGRATION. Symfony/Doctrine migrations (Phase 2) are the sole
-- authority for schema objects (tables, indexes, foreign keys, constraints).
-- PostgreSQL roles and grants are infrastructure (infra/ bootstrap, D-15) and
-- are deliberately absent here. This file is the normative reference that the
-- Doctrine entities, the Python validator and the Go delivery daemon are built
-- against; Phase 2 migrations must reproduce it. Never apply it to a real
-- database.
--
-- Conventions (docs/architecture/conventions.md):
--   * ids: uuid, UUIDv7 generated by the writing application (no DB default).
--   * timestamps: timestamptz, UTC.
--   * enums: text + CHECK, values from docs/contracts/status-vocabulary.yaml.
--   * JSON: jsonb.
--   * Foreign keys: NO ACTION on delete (history is never cascaded away).
--   * Address normalisation (D-18): trim surrounding whitespace, preserve the
--     local part exactly, lower-case the domain. Performed by the application;
--     CHECKs below only verify the domain is lower-case.
--   * Leased work (D-03): claimed_by, lease_expires_at, attempt_count,
--     next_attempt_at, last_error.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tenancy, people, domains and authentication
-- -----------------------------------------------------------------------------

CREATE TABLE clients (
    id             uuid        PRIMARY KEY,
    company_name   text        NOT NULL,
    contact_email  text        NOT NULL,
    status         text        NOT NULL DEFAULT 'pending_approval'
        CHECK (status IN ('pending_approval', 'active', 'throttled', 'suspended', 'closed')),
    plan           text        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    -- D-30: operator-granted capability to report recipient global opt-outs. Never set by the client.
    can_submit_global_suppressions  boolean  NOT NULL DEFAULT false
);

-- Dashboard accounts (D-12). Passwordless: sign-in is by single-use emailed link
-- (auth_login_tokens). API keys are never browser credentials. Installation-wide
-- roles are in user_roles; client access is in client_memberships.
CREATE TABLE users (
    id             uuid        PRIMARY KEY,
    email          text        NOT NULL,                             -- login identifier
    display_name   text        NULL,
    status         text        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at     timestamptz NOT NULL DEFAULT now(),
    last_login_at  timestamptz NULL,
    disabled_at    timestamptz NULL
);
-- Login identity rule: unique case-insensitively. Never reused as the SMTP
-- mailbox-normalisation rule (D-18).
CREATE UNIQUE INDEX users_email_uq ON users (lower(email));

CREATE TABLE client_memberships (
    id          uuid        PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES users (id),
    client_id   uuid        NOT NULL REFERENCES clients (id),
    role        text        NOT NULL CHECK (role IN ('admin', 'member', 'viewer')),
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX client_memberships_user_client_uq ON client_memberships (user_id, client_id);
CREATE INDEX client_memberships_client_idx ON client_memberships (client_id);

-- Installation-wide roles and the permission keys they grant (App\Access\PermissionCatalog;
-- keys are code, not rows). Built-in: ADMIN (every permission by definition, no rows) and
-- OPERATOR (seeded with every PLATFORM.* permission, editable). Specification 2.7.
CREATE TABLE roles (
    id           uuid        PRIMARY KEY,
    role_key     text        NOT NULL CHECK (role_key ~ '^[A-Z][A-Z0-9_]{1,63}$'),
    name         text        NOT NULL CHECK (length(name) BETWEEN 1 AND 100),
    description  text        NOT NULL DEFAULT '',
    is_builtin   boolean     NOT NULL DEFAULT false,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX roles_key_uq ON roles (role_key);

CREATE TABLE role_permissions (
    id              uuid        PRIMARY KEY,
    role_id         uuid        NOT NULL REFERENCES roles (id),
    permission_key  text        NOT NULL CHECK (permission_key ~ '^[A-Z][A-Z_]*(\.[A-Z][A-Z_]*)+$'),
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX role_permissions_role_permission_uq ON role_permissions (role_id, permission_key);

CREATE TABLE user_roles (
    id           uuid        PRIMARY KEY,
    user_id      uuid        NOT NULL REFERENCES users (id),
    role_id      uuid        NOT NULL REFERENCES roles (id),
    assigned_by  uuid        NULL REFERENCES users (id),
    assigned_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX user_roles_user_role_uq ON user_roles (user_id, role_id);
CREATE INDEX user_roles_role_idx ON user_roles (role_id);

-- Single-use emailed sign-in links. Only the SHA-256 of the token is stored; the
-- rows double as the request history for the per-address and per-IP rate limits
-- (the IP is stored only as a keyed hash). user_id is NULL when the link was
-- issued to APP_ADMIN_EMAIL before that account existed.
CREATE TABLE auth_login_tokens (
    id                 uuid        PRIMARY KEY,
    email              text        NOT NULL,
    user_id            uuid        NULL REFERENCES users (id),
    token_hash         text        NOT NULL CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    return_path        text        NULL CHECK (return_path IS NULL OR return_path ~ '^/dashboard(/[^/]|$)'),
    requested_ip_hash  text        NOT NULL CHECK (requested_ip_hash ~ '^[0-9a-f]{64}$'),
    created_at         timestamptz NOT NULL DEFAULT now(),
    expires_at         timestamptz NOT NULL,
    used_at            timestamptz NULL,
    CONSTRAINT auth_login_tokens_expiry_after_creation CHECK (expires_at > created_at)
);
CREATE UNIQUE INDEX auth_login_tokens_hash_uq ON auth_login_tokens (token_hash);
CREATE INDEX auth_login_tokens_email_created_idx ON auth_login_tokens (lower(email), created_at);
CREATE INDEX auth_login_tokens_ip_created_idx ON auth_login_tokens (requested_ip_hash, created_at);
CREATE INDEX auth_login_tokens_user_idx ON auth_login_tokens (user_id) WHERE user_id IS NOT NULL;

-- Sending domains with DNS TXT verification and DKIM status (D-13, D-26).
-- TXT record: _smarthost-verification.<domain>  "smarthost-verification=<token>".
-- The token is published in DNS, is not an authentication secret and is stored as-is.
CREATE TABLE sending_domains (
    id                  uuid        PRIMARY KEY,
    client_id           uuid        NOT NULL REFERENCES clients (id),
    domain              text        NOT NULL CHECK (domain = lower(domain) AND position('@' IN domain) = 0),
    status              text        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'disabled')),
    verification_token  text        NOT NULL CHECK (verification_token ~ '^[A-Za-z0-9_-]{22,}$'),  -- >= 128 bits base64url
    verified_at         timestamptz NULL,
    last_checked_at     timestamptz NULL,
    last_check_error    text        NULL,
    dkim_selector       text        NULL,
    dkim_status         text        NOT NULL DEFAULT 'not_configured'
        CHECK (dkim_status IN ('not_configured', 'pending_dns', 'active', 'disabled')),
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT sending_domains_verified_has_time CHECK (status <> 'verified' OR verified_at IS NOT NULL),
    CONSTRAINT sending_domains_dkim_has_selector CHECK (dkim_status = 'not_configured' OR dkim_selector IS NOT NULL)
);
CREATE UNIQUE INDEX sending_domains_client_domain_uq ON sending_domains (client_id, domain);
CREATE INDEX sending_domains_domain_idx ON sending_domains (domain);

CREATE TABLE api_keys (
    id            uuid        PRIMARY KEY,
    client_id     uuid        NOT NULL REFERENCES clients (id),
    key_hash      text        NOT NULL CHECK (key_hash ~ '^[0-9a-f]{64}$'),  -- SHA-256 hex
    key_prefix    text        NOT NULL,                                       -- non-secret display prefix
    name          text        NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_used_at  timestamptz NULL,
    revoked_at    timestamptz NULL
);
CREATE UNIQUE INDEX api_keys_key_hash_uq ON api_keys (key_hash);
CREATE INDEX api_keys_client_id_idx ON api_keys (client_id);

-- -----------------------------------------------------------------------------
-- Validation
-- -----------------------------------------------------------------------------

CREATE TABLE validation_jobs (
    id                          uuid        PRIMARY KEY,
    client_id                   uuid        NOT NULL REFERENCES clients (id),
    external_reference          text        NULL,
    idempotency_key             text        NOT NULL,
    request_hash                text        NOT NULL,                -- detects key reuse with a different body
    status                      text        NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'processing', 'completed', 'failed', 'cancelled')),
    submitted_at                timestamptz NOT NULL DEFAULT now(),
    started_at                  timestamptz NULL,
    completed_at                timestamptz NULL,
    total_addresses             integer     NOT NULL CHECK (total_addresses BETWEEN 1 AND 10000),
    processed_count             integer     NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    classification_counts_json  jsonb       NOT NULL DEFAULT '{}'::jsonb
);
CREATE UNIQUE INDEX validation_jobs_client_idempotency_uq ON validation_jobs (client_id, idempotency_key);
CREATE INDEX validation_jobs_client_status_idx ON validation_jobs (client_id, status);
CREATE INDEX validation_jobs_client_external_ref_idx ON validation_jobs (client_id, external_reference)
    WHERE external_reference IS NOT NULL;

CREATE TABLE validation_addresses (
    id                          uuid        PRIMARY KEY,
    job_id                      uuid        NOT NULL REFERENCES validation_jobs (id),
    external_address_reference  text        NULL,                    -- D-21: opaque client reference per address
    original_address            text        NOT NULL,                -- verbatim input, never modified
    normalized_address          text        NULL,
    syntax_status               text        NULL CHECK (syntax_status IN ('valid', 'invalid')),
    domain_status               text        NULL CHECK (domain_status IN (
        'mx', 'null_mx', 'address_fallback', 'no_mail_host', 'nxdomain',
        'temporary_failure', 'invalid_response', 'skipped')),
    smtp_status                 text        NULL CHECK (smtp_status IN (
        'accepted', 'rejected', 'temporary_failure', 'blocked', 'timeout',
        'connection_failed', 'inconclusive', 'skipped')),
    is_role                     boolean     NULL,
    is_disposable               boolean     NULL,
    is_catch_all_or_accept_all  boolean     NULL,
    is_domain_typo_suspected    boolean     NULL,
    suggested_address           text        NULL,                    -- suggestion only (D-04)
    suggestion_reason_code      text        NULL CHECK (suggestion_reason_code IN (
        'provider_domain_edit_distance', 'transposition', 'tld_typo',
        'legacy_domain_alias', 'other_domain_typo_rule')),
    suggestion_confidence       text        NULL CHECK (suggestion_confidence IN ('low', 'medium', 'high')),
    overall_classification      text        NULL CHECK (overall_classification IN (
        'deliverable', 'probably_deliverable', 'undeliverable',
        'temporarily_unverifiable', 'unknown', 'risky')),
    confidence                  text        NULL CHECK (confidence IN ('low', 'medium', 'high')),
    diagnostic_code             text        NULL,
    diagnostic_text             text        NULL,
    checked_at                  timestamptz NULL,
    -- Leased work (validator only; not exposed by the API)
    processing_state            text        NOT NULL DEFAULT 'pending'
        CHECK (processing_state IN ('pending', 'claimed', 'retry_scheduled', 'done')),
    claimed_by                  text        NULL,
    lease_expires_at            timestamptz NULL,
    attempt_count               integer     NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at             timestamptz NULL,
    last_error                  text        NULL,
    CONSTRAINT validation_addresses_done_has_result CHECK (
        processing_state <> 'done' OR (overall_classification IS NOT NULL AND checked_at IS NOT NULL)),
    CONSTRAINT validation_addresses_claim_has_lease CHECK (
        processing_state <> 'claimed' OR (claimed_by IS NOT NULL AND lease_expires_at IS NOT NULL)),
    CONSTRAINT validation_addresses_suggestion_complete CHECK (
        (suggested_address IS NULL) = (suggestion_reason_code IS NULL)
        AND (suggested_address IS NULL) = (suggestion_confidence IS NULL))
);
CREATE INDEX validation_addresses_job_id_idx ON validation_addresses (job_id, id);
CREATE INDEX validation_addresses_normalized_address_idx ON validation_addresses (normalized_address);
CREATE INDEX validation_addresses_claimable_idx ON validation_addresses (processing_state, next_attempt_at, lease_expires_at)
    WHERE processing_state <> 'done';

CREATE TABLE validation_evidence (
    id                     uuid        PRIMARY KEY,
    validation_address_id  uuid        NOT NULL REFERENCES validation_addresses (id),
    evidence_type          text        NOT NULL CHECK (evidence_type IN (
        'dns_mx', 'dns_address', 'smtp_connect', 'smtp_ehlo', 'smtp_mail_from',
        'smtp_rcpt_to', 'smtp_accept_all_probe')),
    provider_host          text        NULL,
    response_code          smallint    NULL,
    enhanced_status_code   text        NULL,
    detail_json            jsonb       NOT NULL DEFAULT '{}'::jsonb,
    occurred_at            timestamptz NOT NULL
);
CREATE INDEX validation_evidence_address_occurred_idx ON validation_evidence (validation_address_id, occurred_at);

CREATE TABLE disposable_domains (
    domain            text        PRIMARY KEY CHECK (domain = lower(domain)),
    source            text        NOT NULL,
    added_at          timestamptz NOT NULL DEFAULT now(),
    last_verified_at  timestamptz NULL
);

-- -----------------------------------------------------------------------------
-- Sending
-- -----------------------------------------------------------------------------

-- Job-level delivery parameters only; all content is per recipient (D-08).
CREATE TABLE send_jobs (
    id                     uuid        PRIMARY KEY,
    client_id              uuid        NOT NULL REFERENCES clients (id),   -- from the API credential only (D-19)
    external_reference     text        NOT NULL,
    idempotency_key        text        NOT NULL,
    request_hash           text        NOT NULL,
    message_class          text        NOT NULL CHECK (message_class IN ('transactional', 'subscription')),
    list_id                text        NULL,                         -- RFC 2919 List-Id; mandatory for subscription
    sending_domain_id      uuid        NOT NULL REFERENCES sending_domains (id),
    sender_email           text        NOT NULL,
    sender_name            text        NULL,
    reply_to_email         text        NULL,                         -- D-25 optional job-level Reply-To
    reply_to_name          text        NULL,
    track_opens            boolean     NOT NULL DEFAULT false,
    track_clicks           boolean     NOT NULL DEFAULT false,
    status                 text        NOT NULL DEFAULT 'collecting'
        CHECK (status IN ('collecting', 'queued', 'processing', 'dispatched', 'completed', 'failed', 'cancelled')),
    created_at             timestamptz NOT NULL DEFAULT now(),
    queued_at              timestamptz NULL,                         -- set by submit
    started_at             timestamptz NULL,
    dispatch_completed_at  timestamptz NULL,
    completed_at           timestamptz NULL,
    total_recipients       integer     NOT NULL DEFAULT 0 CHECK (total_recipients BETWEEN 0 AND 10000),
    summary_counts_json    jsonb       NOT NULL DEFAULT '{}'::jsonb,
    -- Leased work (delivery daemon only)
    claimed_by             text        NULL,
    lease_expires_at       timestamptz NULL,
    attempt_count          integer     NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_error             text        NULL,
    CONSTRAINT send_jobs_list_id_by_class CHECK ((message_class = 'subscription') = (list_id IS NOT NULL)),
    CONSTRAINT send_jobs_reply_to_complete CHECK (reply_to_name IS NULL OR reply_to_email IS NOT NULL),
    CONSTRAINT send_jobs_sealed CHECK (
        status IN ('collecting', 'cancelled') OR (queued_at IS NOT NULL AND total_recipients >= 1)),
    CONSTRAINT send_jobs_dispatched_has_time CHECK (
        status NOT IN ('dispatched', 'completed') OR dispatch_completed_at IS NOT NULL),
    CONSTRAINT send_jobs_completed_has_time CHECK (status <> 'completed' OR completed_at IS NOT NULL)
);
CREATE UNIQUE INDEX send_jobs_client_idempotency_uq ON send_jobs (client_id, idempotency_key);
CREATE INDEX send_jobs_client_status_idx ON send_jobs (client_id, status);
CREATE INDEX send_jobs_client_external_ref_idx ON send_jobs (client_id, external_reference);
CREATE INDEX send_jobs_claimable_idx ON send_jobs (queued_at, lease_expires_at) WHERE status IN ('queued', 'processing');
CREATE INDEX send_jobs_awaiting_completion_idx ON send_jobs (dispatch_completed_at) WHERE status = 'dispatched';
CREATE INDEX send_jobs_collecting_idx ON send_jobs (created_at) WHERE status = 'collecting';   -- abandoned-job cleanup

-- One row per accepted recipient-upload request (D-24); carries batch idempotency.
CREATE TABLE send_job_recipient_batches (
    id               uuid        PRIMARY KEY,
    send_job_id      uuid        NOT NULL REFERENCES send_jobs (id),
    idempotency_key  text        NOT NULL,
    request_hash     text        NOT NULL,
    recipient_count  integer     NOT NULL CHECK (recipient_count BETWEEN 1 AND 500),
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX send_job_recipient_batches_job_key_uq ON send_job_recipient_batches (send_job_id, idempotency_key);

-- Staged recipient input written by Symfony (D-01). Immutable once the job is
-- sealed, except that rendered content is purged (D-14). Holds no SMTP state.
CREATE TABLE send_job_recipients (
    id                            uuid        PRIMARY KEY,
    send_job_id                   uuid        NOT NULL REFERENCES send_jobs (id),
    batch_id                      uuid        NOT NULL REFERENCES send_job_recipient_batches (id),
    external_recipient_reference  text        NOT NULL,
    email_address                 text        NOT NULL,              -- as submitted
    normalized_address            text        NOT NULL,              -- D-18 form; duplicate detection and suppression matching
    subject                       text        NULL,                  -- rendered by the client; NULL once purged
    html_body                     text        NULL,                  -- rendered by the client; NULL once purged
    text_body                     text        NULL,                  -- rendered by the client; NULL once purged
    unsubscribe_url               text        NULL CHECK (unsubscribe_url ~ '^https://'),  -- mandatory for subscription (API-enforced)
    content_bytes                 integer     NOT NULL CHECK (content_bytes >= 0),          -- retained after purge
    content_sha256                text        NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),  -- retained after purge
    content_purged_at             timestamptz NULL,
    created_at                    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT send_job_recipients_content_state CHECK (
        (content_purged_at IS NULL AND subject IS NOT NULL AND (html_body IS NOT NULL OR text_body IS NOT NULL))
     OR (content_purged_at IS NOT NULL AND subject IS NULL AND html_body IS NULL AND text_body IS NULL))
);
CREATE INDEX send_job_recipients_send_job_idx ON send_job_recipients (send_job_id, id);
CREATE UNIQUE INDEX send_job_recipients_job_address_uq ON send_job_recipients (send_job_id, normalized_address);
CREATE INDEX send_job_recipients_unpurged_idx ON send_job_recipients (created_at) WHERE content_purged_at IS NULL;

-- One row per recipient message; created by Go (D-01).
CREATE TABLE messages (
    id                            uuid        PRIMARY KEY,
    send_job_id                   uuid        NOT NULL REFERENCES send_jobs (id),
    send_job_recipient_id         uuid        NOT NULL REFERENCES send_job_recipients (id),
    external_recipient_reference  text        NOT NULL,
    recipient_address             text        NOT NULL,              -- normalised address used for RCPT TO
    verp_token                    text        NOT NULL,
    return_path                   text        NOT NULL,              -- envelope MAIL FROM, e.g. bounce+TOKEN@bounce-domain
    tracking_token                text        NULL CHECK (tracking_token ~ '^[A-Za-z0-9_-]{32,}$'),  -- >= 192-bit random, base64url; NULL when tracking off
    postfix_queue_id              text        NULL,
    current_status                text        NOT NULL DEFAULT 'created'
        CHECK (current_status IN ('created', 'queued', 'submitted', 'deferred', 'outcome_unknown',
                                  'remote_accepted', 'soft_bounced', 'hard_bounced', 'complained',
                                  'failed', 'suppressed')),
    created_at                    timestamptz NOT NULL DEFAULT now(),
    resolved_at                   timestamptz NULL
);
CREATE INDEX messages_send_job_id_idx ON messages (send_job_id, id);
CREATE INDEX messages_send_job_status_idx ON messages (send_job_id, current_status);
CREATE UNIQUE INDEX messages_send_job_recipient_uq ON messages (send_job_recipient_id);
CREATE UNIQUE INDEX messages_verp_token_uq ON messages (verp_token);
CREATE UNIQUE INDEX messages_tracking_token_uq ON messages (tracking_token) WHERE tracking_token IS NOT NULL;
CREATE INDEX messages_postfix_queue_id_idx ON messages (postfix_queue_id) WHERE postfix_queue_id IS NOT NULL;
CREATE INDEX messages_unresolved_idx ON messages (current_status, created_at)   -- D-27 reconciliation candidates
    WHERE current_status IN ('queued', 'submitted', 'deferred');
-- D-30: global repeated-soft-bounce evaluation and recipient-based DSN correlation.
CREATE INDEX messages_recipient_address_idx ON messages (recipient_address);

-- Server-side click map written by Go (D-09): /t/c/{tracking_token}/{link_index}.
CREATE TABLE message_links (
    id          uuid        PRIMARY KEY,
    message_id  uuid        NOT NULL REFERENCES messages (id),
    link_index  integer     NOT NULL CHECK (link_index >= 1),
    target_url  text        NOT NULL CHECK (target_url ~* '^https?://'),
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX message_links_message_link_uq ON message_links (message_id, link_index);

CREATE TABLE message_events (
    id                    uuid        PRIMARY KEY,
    message_id            uuid        NOT NULL REFERENCES messages (id),
    event_type            text        NOT NULL CHECK (event_type IN (
        'message_created', 'message_queued', 'message_suppressed', 'submission_failed',
        'submitted_to_postfix', 'postfix_queued', 'delivery_attempt', 'deferred',
        'connection_failure', 'remote_accepted', 'soft_bounce', 'hard_bounce',
        'complaint', 'transport_outcome_unknown', 'open_recorded', 'click_recorded',
        'dsn_unmatched')),
    event_source          text        NOT NULL CHECK (event_source IN (                   -- D-06
        'delivery_daemon', 'postfix_submission', 'postfix_log', 'dsn_spool',
        'unmatched_dsn_resolution', 'queue_reconciliation', 'tracking_endpoint')),
    source_event_key      text        NULL,                          -- stable identity within the source
    failure_scope         text        NULL CHECK (failure_scope IN (                      -- D-18
        'recipient', 'domain', 'provider_policy', 'connection', 'dns', 'infrastructure', 'unknown')),
    smtp_code             smallint    NULL CHECK (smtp_code BETWEEN 200 AND 599),
    enhanced_status_code  text        NULL CHECK (enhanced_status_code ~ '^[245]\.[0-9]{1,3}\.[0-9]{1,3}$'),
    remote_host           text        NULL,
    diagnostic            text        NULL,
    metadata_json         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    occurred_at           timestamptz NOT NULL,                      -- when it happened
    recorded_at           timestamptz NOT NULL DEFAULT now(),        -- when it was inserted
    CONSTRAINT message_events_tracking_unkeyed CHECK (event_source <> 'tracking_endpoint' OR source_event_key IS NULL),
    CONSTRAINT message_events_transport_keyed CHECK (event_source = 'tracking_endpoint' OR source_event_key IS NOT NULL),
    CONSTRAINT message_events_failure_scope_applicable CHECK (
        failure_scope IS NULL OR event_type IN ('deferred', 'connection_failure', 'soft_bounce', 'hard_bounce'))
);
CREATE INDEX message_events_message_occurred_idx ON message_events (message_id, occurred_at, id);
CREATE UNIQUE INDEX message_events_source_key_uq ON message_events (event_source, source_event_key)
    WHERE source_event_key IS NOT NULL;
CREATE INDEX message_events_soft_bounce_idx ON message_events (message_id, occurred_at)   -- D-18 rule evaluation
    WHERE event_type IN ('soft_bounce', 'remote_accepted');
-- Phase 6: recorded-open/click aggregates and the tracking endpoint's per-message check.
CREATE INDEX message_events_engagement_idx ON message_events (message_id, occurred_at)
    WHERE event_type IN ('open_recorded', 'click_recorded');

-- DSNs that resolve to no message (D-05). Operator-scoped; retained after resolution.
CREATE TABLE unmatched_dsns (
    id                       uuid        PRIMARY KEY,
    received_at              timestamptz NOT NULL,
    spool_ingest_key         text        NOT NULL,                   -- Maildir unique file name; stable across retry (D-06)
    content_sha256           text        NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),  -- diagnostic only, not a dedup key
    classification           text        NOT NULL CHECK (classification IN (
        'hard_bounce', 'soft_bounce', 'deferred', 'connection_failure',
        'complaint', 'malformed_or_unmatched_dsn')),
    status                   text        NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'match_requested', 'matched', 'dismissed')),
    verp_token               text        NULL,
    original_recipient       text        NULL,
    final_recipient          text        NULL,
    postfix_queue_id         text        NULL,
    reporting_mta            text        NULL,
    enhanced_status_code     text        NULL,
    raw_message              text        NOT NULL,                   -- DSN as received (RET=HDRS keeps it small)
    detail_json              jsonb       NOT NULL DEFAULT '{}'::jsonb,
    matched_message_id       uuid        NULL REFERENCES messages (id),
    resolution_requested_by  uuid        NULL REFERENCES users (id), -- operator who identified the message
    resolution_requested_at  timestamptz NULL,
    resolution_event_id      uuid        NULL REFERENCES message_events (id),
    resolution_note          text        NULL,
    resolved_at              timestamptz NULL,
    CONSTRAINT unmatched_dsns_match_requested CHECK (
        status NOT IN ('match_requested', 'matched')
        OR (matched_message_id IS NOT NULL AND resolution_requested_by IS NOT NULL AND resolution_requested_at IS NOT NULL)),
    CONSTRAINT unmatched_dsns_matched_complete CHECK (
        status <> 'matched' OR (resolution_event_id IS NOT NULL AND resolved_at IS NOT NULL)),
    -- A dismissal needs its time and the operator's written reason (Phase 5).
    CONSTRAINT unmatched_dsns_dismissed_resolved CHECK (
        status <> 'dismissed' OR (resolved_at IS NOT NULL AND resolution_note IS NOT NULL))
);
CREATE INDEX unmatched_dsns_status_received_idx ON unmatched_dsns (status, received_at);
CREATE UNIQUE INDEX unmatched_dsns_spool_key_uq ON unmatched_dsns (spool_ingest_key);

-- Persistent Go ingestion position (D-16): log generation identity + position
-- within it. A raw byte offset alone is not sufficient across rotation.
CREATE TABLE delivery_ingest_cursors (
    source         text        PRIMARY KEY,                          -- e.g. 'postfix_log'
    generation_id  text        NOT NULL,                             -- identity of the log generation (Phase 1 verification)
    position       bigint      NOT NULL CHECK (position >= 0),       -- position within that generation
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- Suppression and reputation
-- -----------------------------------------------------------------------------

-- D-30: automatic suppressions (hard_bounce, complaint, repeated_soft_bounce) and
-- recipient global opt-outs are global (client_id NULL). client_id only scopes a
-- row; the client that reported a global opt-out is source_client_id. Rows are
-- lifted (lifted_at), never deleted, except by configured retention.
CREATE TABLE suppressions (
    id                 uuid        PRIMARY KEY,
    client_id          uuid        NULL REFERENCES clients (id),     -- NULL = global suppression
    address_or_domain  text        NOT NULL,                         -- D-18 normalised
    scope_type         text        NOT NULL CHECK (scope_type IN ('address', 'domain')),
    reason             text        NOT NULL CHECK (reason IN (
        'hard_bounce', 'complaint', 'repeated_soft_bounce', 'operator_block', 'client_abuse_block',
        'recipient_global_opt_out')),
    source_message_id  uuid        NULL REFERENCES messages (id),
    created_at         timestamptz NOT NULL DEFAULT now(),
    expires_at         timestamptz NULL,
    lifted_at          timestamptz NULL,
    -- Provenance (D-30)
    source_event_id    uuid        NULL REFERENCES message_events (id),  -- authoritative event of a system suppression
    source_client_id   uuid        NULL REFERENCES clients (id),     -- client that reported a global opt-out
    external_reference text        NULL,                             -- optional opaque reference of the creating request
    -- D-18: only the domain is lower-cased; the local part is never case-folded.
    CONSTRAINT suppressions_normalised CHECK (
        (scope_type = 'domain'  AND address_or_domain = lower(address_or_domain)
                                AND position('@' IN address_or_domain) = 0)
     OR (scope_type = 'address' AND address_or_domain ~ '@[^@]+$'
                                AND substring(address_or_domain FROM '@([^@]+)$')
                                    = lower(substring(address_or_domain FROM '@([^@]+)$')))),
    -- A client-reported opt-out (and only it) names its reporter; it is always a
    -- global address suppression. Its requests are in global_suppression_requests.
    CONSTRAINT suppressions_opt_out_provenance CHECK (
        (reason = 'recipient_global_opt_out') = (source_client_id IS NOT NULL)
        AND (external_reference IS NULL OR source_client_id IS NOT NULL)
        AND (reason <> 'recipient_global_opt_out' OR (client_id IS NULL AND scope_type = 'address'))),
    -- Indefinite reasons never expire; repeated_soft_bounce is the temporary one.
    CONSTRAINT suppressions_indefinite_reasons CHECK (
        reason NOT IN ('hard_bounce', 'complaint', 'recipient_global_opt_out') OR expires_at IS NULL),
    CONSTRAINT suppressions_source_event_has_message CHECK (source_event_id IS NULL OR source_message_id IS NOT NULL)
);
CREATE INDEX suppressions_address_or_domain_scope_idx ON suppressions (address_or_domain, scope_type);
CREATE INDEX suppressions_client_idx ON suppressions (client_id);
-- One active global hard_bounce / complaint row per address (concurrent evidence cannot duplicate it).
CREATE UNIQUE INDEX suppressions_global_address_reason_active_uq ON suppressions (address_or_domain, reason)
    WHERE client_id IS NULL AND scope_type = 'address' AND lifted_at IS NULL AND reason IN ('hard_bounce', 'complaint');
-- One active opt-out per reporting client and address.
CREATE UNIQUE INDEX suppressions_source_client_address_active_uq ON suppressions (source_client_id, address_or_domain)
    WHERE reason = 'recipient_global_opt_out' AND lifted_at IS NULL;
CREATE INDEX suppressions_source_message_idx ON suppressions (source_message_id) WHERE source_message_id IS NOT NULL;

-- D-38: durable idempotency of recipient global opt-out requests, independent of
-- the suppression row. One row per accepted (client, operation, Idempotency-Key):
-- the canonical request hash, the suppression it resulted in and the original
-- status (201 created, 200 already active). Never updated, so a key keeps its
-- meaning after the suppression is lifted.
CREATE TABLE global_suppression_requests (
    id                  uuid        PRIMARY KEY,
    client_id           uuid        NOT NULL REFERENCES clients (id),     -- the authenticated reporting client
    operation           text        NOT NULL CHECK (operation IN ('create_global_opt_out')),
    idempotency_key     text        NOT NULL,
    request_hash        text        NOT NULL,                             -- canonical JSON hash (as other idempotent requests)
    suppression_id      uuid        NOT NULL REFERENCES suppressions (id),
    response_status     smallint    NOT NULL CHECK (response_status IN (200, 201)),
    external_reference  text        NULL,                                 -- this request's optional client reference
    created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX global_suppression_requests_client_operation_key_uq ON global_suppression_requests (client_id, operation, idempotency_key);
CREATE INDEX global_suppression_requests_suppression_idx ON global_suppression_requests (suppression_id);

CREATE TABLE domain_reputation (
    id                  uuid        PRIMARY KEY,
    client_id           uuid        NULL REFERENCES clients (id),    -- NULL = platform-wide aggregate
    destination_domain  text        NOT NULL CHECK (destination_domain = lower(destination_domain)),
    metrics_json        jsonb       NOT NULL DEFAULT '{}'::jsonb,
    last_updated_at     timestamptz NOT NULL
);
CREATE UNIQUE INDEX domain_reputation_client_domain_uq
    ON domain_reputation (client_id, destination_domain) NULLS NOT DISTINCT;

-- -----------------------------------------------------------------------------
-- Metering, webhooks, audit
-- -----------------------------------------------------------------------------

CREATE TABLE usage_records (
    id              uuid        PRIMARY KEY,
    client_id       uuid        NOT NULL REFERENCES clients (id),
    usage_type      text        NOT NULL CHECK (usage_type IN ('validation_address', 'message_submitted')),
    quantity        bigint      NOT NULL CHECK (quantity > 0),
    reference_type  text        NOT NULL CHECK (reference_type IN ('validation_job', 'send_job', 'message')),
    reference_id    uuid        NOT NULL,
    occurred_at     timestamptz NOT NULL
);
CREATE INDEX usage_records_client_occurred_idx ON usage_records (client_id, occurred_at);
CREATE INDEX usage_records_reference_idx ON usage_records (reference_type, reference_id);

-- Client webhook registration (D-10). Secrets are encrypted with the
-- application keyring (APP_ENCRYPTION_KEYS); *_key_id names the key used.
CREATE TABLE webhook_endpoints (
    id                                  uuid        PRIMARY KEY,
    client_id                           uuid        NOT NULL REFERENCES clients (id),
    url                                 text        NOT NULL CHECK (url ~* '^https?://'),  -- https enforced by the app outside development
    status                              text        NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
    subscribed_event_types              jsonb       NOT NULL CHECK (jsonb_typeof(subscribed_event_types) = 'array'),
    signing_secret_ciphertext           text        NOT NULL,
    signing_secret_key_id               text        NOT NULL,
    signing_secret_created_at           timestamptz NOT NULL DEFAULT now(),
    previous_signing_secret_ciphertext  text        NULL,
    previous_signing_secret_key_id      text        NULL,
    previous_signing_secret_expires_at  timestamptz NULL,
    created_at                          timestamptz NOT NULL DEFAULT now(),
    updated_at                          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT webhook_endpoints_previous_secret_complete CHECK (
        (previous_signing_secret_ciphertext IS NULL) = (previous_signing_secret_expires_at IS NULL)
        AND (previous_signing_secret_ciphertext IS NULL) = (previous_signing_secret_key_id IS NULL))
);
CREATE INDEX webhook_endpoints_client_idx ON webhook_endpoints (client_id);

-- Transactional outbox (D-22): producers insert in the same transaction as the
-- state change; only the Symfony webhook worker consumes it. id = Smarthost-Event-Id.
CREATE TABLE webhook_events (
    id             uuid        PRIMARY KEY,
    client_id      uuid        NOT NULL REFERENCES clients (id),
    event_type     text        NOT NULL CHECK (event_type IN (
        'validation.completed', 'validation.failed', 'send.completed', 'send.failed',
        'message.hard_bounced', 'message.complained', 'webhook.test')),
    subject_type   text        NOT NULL CHECK (subject_type IN ('validation_job', 'send_job', 'message', 'webhook_endpoint')),
    subject_id     uuid        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    fanned_out_at  timestamptz NULL,
    -- webhook.test is always addressed to exactly one endpoint, and only webhook.test has that subject.
    CONSTRAINT webhook_events_test_subject CHECK (
        (event_type = 'webhook.test') = (subject_type = 'webhook_endpoint'))
);
CREATE INDEX webhook_events_pending_fanout_idx ON webhook_events (created_at) WHERE fanned_out_at IS NULL;
CREATE UNIQUE INDEX webhook_events_once_uq ON webhook_events (event_type, subject_id)
    WHERE event_type <> 'webhook.test';
CREATE INDEX webhook_events_created_idx ON webhook_events (created_at, id);  -- operator outbox list (Phase 7)

CREATE TABLE webhook_deliveries (
    id                    uuid        PRIMARY KEY,
    client_id             uuid        NOT NULL REFERENCES clients (id),
    webhook_event_id      uuid        NOT NULL REFERENCES webhook_events (id),
    webhook_endpoint_id   uuid        NOT NULL REFERENCES webhook_endpoints (id),
    event_type            text        NOT NULL CHECK (event_type IN (
        'validation.completed', 'validation.failed', 'send.completed', 'send.failed',
        'message.hard_bounced', 'message.complained', 'webhook.test')),
    payload_json          jsonb       NOT NULL,                      -- exact body, needed for retries
    payload_hash          text        NOT NULL,
    status                text        NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'delivered', 'failed')),
    attempt_count         integer     NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at       timestamptz NULL,
    claimed_by            text        NULL,
    lease_expires_at      timestamptz NULL,
    last_response_status  smallint    NULL,
    last_error            text        NULL,
    delivered_at          timestamptz NULL,
    created_at            timestamptz NOT NULL DEFAULT now(),
    -- Phase 7 (specification 2.8)
    updated_at            timestamptz NOT NULL DEFAULT now(),
    last_attempt_at       timestamptz NULL,
    last_response_excerpt text        NULL CHECK (length(last_response_excerpt) <= 1024),  -- bounded diagnostics only
    CONSTRAINT webhook_deliveries_delivered_has_time CHECK (status <> 'delivered' OR delivered_at IS NOT NULL),
    -- A claim is a lease; attempt_count (incremented by the claim) fences the attempt's result.
    CONSTRAINT webhook_deliveries_lease_complete CHECK ((claimed_by IS NULL) = (lease_expires_at IS NULL)),
    CONSTRAINT webhook_deliveries_final_unclaimed CHECK (status = 'pending' OR claimed_by IS NULL)
);
CREATE INDEX webhook_deliveries_due_idx ON webhook_deliveries (status, next_attempt_at) WHERE status = 'pending';
CREATE INDEX webhook_deliveries_client_created_idx ON webhook_deliveries (client_id, created_at);
CREATE UNIQUE INDEX webhook_deliveries_event_endpoint_uq ON webhook_deliveries (webhook_event_id, webhook_endpoint_id);
-- Phase 7 query-plan review: per-endpoint counts; cross-client lists and the bounded summary.
CREATE INDEX webhook_deliveries_endpoint_status_idx ON webhook_deliveries (webhook_endpoint_id, status, created_at);
CREATE INDEX webhook_deliveries_created_idx ON webhook_deliveries (created_at, id);

-- One row per webhook-worker process: liveness and counters for the operator dashboard.
CREATE TABLE webhook_worker_heartbeats (
    worker_id             text        PRIMARY KEY,
    version               text        NOT NULL,
    started_at            timestamptz NOT NULL,
    last_seen_at          timestamptz NOT NULL,
    stopped_at            timestamptz NULL,
    attempts              bigint      NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    delivered             bigint      NOT NULL DEFAULT 0 CHECK (delivered >= 0),
    events_fanned_out     bigint      NOT NULL DEFAULT 0 CHECK (events_fanned_out >= 0)
);
CREATE INDEX webhook_worker_heartbeats_seen_idx ON webhook_worker_heartbeats (last_seen_at);

CREATE TABLE audit_log (
    id           uuid        PRIMARY KEY,
    actor_type   text        NOT NULL CHECK (actor_type IN ('user', 'api_key', 'system')),
    actor_id     text        NULL,
    action       text        NOT NULL,
    target_type  text        NOT NULL,
    target_id    text        NULL,
    detail_json  jsonb       NOT NULL DEFAULT '{}'::jsonb,
    occurred_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_target_idx ON audit_log (target_type, target_id, occurred_at);
CREATE INDEX audit_log_occurred_idx ON audit_log (occurred_at);
